"""
MongoDB Collection Shapes — Rehearsal Room

These are not ORM models but typed dataclasses / TypedDicts documenting the
expected shape of each MongoDB collection document.

Why MongoDB for these collections:
  - session_transcripts: large free-form text blobs, variable Q&A structure
  - engagement_frames:   high write volume (~5 docs/sec), flexible per-frame fields
  - generated_reports:   large Markdown documents with nested structure
"""
from typing import Any, Optional
from datetime import datetime


# ─────────────────────────────────────────────────────────────────────────────
# Collection: session_transcripts
# Index: session_id (unique)
#
# One document per session. Appended to in real-time as questions are answered.
# ─────────────────────────────────────────────────────────────────────────────
SESSION_TRANSCRIPT_SHAPE = {
    "_id": "ObjectId",               # MongoDB auto-generated
    "session_id": "str (UUID)",      # FK to PostgreSQL sessions.id
    "user_id": "str (UUID)",
    "created_at": "datetime",
    "updated_at": "datetime",
    "turns": [
        {
            "turn_index": "int",
            "question_id": "str (UUID)",     # FK to question_bank
            "question_text": "str",
            "question_type": "behavioral|technical|dsa|viva",
            "user_answer_text": "str",       # STT transcript or typed answer
            "code_submission": "str | null", # raw code for coding questions
            "code_output": "str | null",
            "answer_duration_secs": "float",
            "started_at": "datetime",
            "finished_at": "datetime",
            "nudges_given": ["str"],         # coaching nudges sent during this turn
        }
    ]
}


# ─────────────────────────────────────────────────────────────────────────────
# Collection: engagement_frames
# Index: (session_id, ts) composite; TTL on ts (30 days)
#
# One document per ~200ms WebSocket metric batch. Very high write volume.
# Schema intentionally flexible — not all fields guaranteed present every frame.
# ─────────────────────────────────────────────────────────────────────────────
ENGAGEMENT_FRAME_SHAPE = {
    "_id": "ObjectId",
    "session_id": "str (UUID)",
    "frame_batch_id": "str",          # client-generated UUID per batch
    "ts": "datetime",                 # server receipt timestamp (TTL index key)
    "client_ts": "float",             # client Unix timestamp ms
    "question_index": "int",          # which question is active

    # Derived from face-api.js (NOT raw image data)
    "gaze_x": "float | null",         # -1.0 (far left) to 1.0 (far right)
    "gaze_y": "float | null",         # -1.0 (up) to 1.0 (down)
    "blink_detected": "bool",
    "smile_prob": "float",            # 0.0 – 1.0
    "head_yaw": "float | null",       # degrees, left-right
    "head_pitch": "float | null",     # degrees, up-down
    "head_roll": "float | null",      # degrees, tilt
    "dominant_expression": "str",     # neutral|happy|surprised|fearful|disgusted|angry|sad
    "face_detected": "bool",

    # Derived engagement score (computed client-side)
    "engagement_score": "float",      # 0.0 – 1.0
}


# ─────────────────────────────────────────────────────────────────────────────
# Collection: generated_reports
# Index: session_id (unique)
#
# One document per completed session. Generated by Gemini post-session.
# Stored as a large Markdown blob + structured metadata.
# ─────────────────────────────────────────────────────────────────────────────
GENERATED_REPORT_SHAPE = {
    "_id": "ObjectId",
    "session_id": "str (UUID)",
    "user_id": "str (UUID)",
    "generated_at": "datetime",
    "status": "pending|generating|done|failed",

    # Structured data
    "engagement_summary": {
        "eye_contact_pct": "float",
        "avg_blink_rate": "float",
        "smile_frequency": "float",
        "head_steadiness": "float",
        "engagement_over_time": [
            {"minute": "int", "score": "float"}
        ]
    },

    # Per-question analysis
    "question_analyses": [
        {
            "question_id": "str",
            "question_text": "str",
            "user_answer": "str",
            "ideal_answer": "str",
            "user_code": "str | null",
            "ideal_code": "str | null",
            "score_out_of_10": "int",
            "feedback": "str",
            "missed_concepts": ["str"],
        }
    ],

    # Full Markdown report (rendered with react-markdown)
    "report_markdown": "str",

    # Improvement plan (separate section)
    "improvement_plan_markdown": "str",
}
